/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp com.qt.yeedon.can.xml -p candbus_interface
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "candbus_interface.h"

/*
 * Implementation of interface class ComQtYeedonCanInterface
 */

ComQtYeedonCanInterface::ComQtYeedonCanInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComQtYeedonCanInterface::~ComQtYeedonCanInterface()
{
}

