/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp com.tiot.dbus.hardkey.xml -p hardkeymonitorinterface_interface
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef HARDKEYMONITORINTERFACE_INTERFACE_H_1539338597
#define HARDKEYMONITORINTERFACE_INTERFACE_H_1539338597

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.tiot.dbus.hardkey
 */
class ComTiotDbusHardkeyInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.tiot.dbus.hardkey"; }

public:
    ComTiotDbusHardkeyInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ComTiotDbusHardkeyInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> sendKeyEvent(const QDBusVariant &msgID, const QVariantList &param)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(msgID) << QVariant::fromValue(param);
        return asyncCallWithArgumentList(QLatin1String("sendKeyEvent"), argumentList);
    }

    inline QDBusPendingReply<> sendKeyEventInt(int msgID, int param)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(msgID) << QVariant::fromValue(param);
        return asyncCallWithArgumentList(QLatin1String("sendKeyEventInt"), argumentList);
    }

    inline QDBusPendingReply<> wakeUp()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("wakeUp"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void sigKeyEvent(int msgID, int param);
    void sigKeyEvent(const QDBusVariant &msgID, const QVariantList &param);
};

namespace com {
  namespace tiot {
    namespace dbus {
      typedef ::ComTiotDbusHardkeyInterface hardkey;
    }
  }
}
#endif
