/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp com.qt.yeedon.call.xml -p sim800_interface
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef SIM800_INTERFACE_H_1534424188
#define SIM800_INTERFACE_H_1534424188

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.qt.yeedon.call
 */
class ComQtYeedonCallInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.qt.yeedon.call"; }

public:
    ComQtYeedonCallInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ComQtYeedonCallInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> pickdown()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("pickdown"), argumentList);
    }

    inline QDBusPendingReply<> pickup()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("pickup"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void broadcastRing();
};

namespace com {
  namespace qt {
    namespace yeedon {
      typedef ::ComQtYeedonCallInterface call;
    }
  }
}
#endif
